task_manager_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todo.views import index, toggle_join_task

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", index),
    path("", include("todo.urls", namespace="todo")),
    path("tasks/<int:pk>/toggle-join-task/", toggle_join_task, name="toggle-join-task")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path

from todo.views import (
    PositionListView,
    PositionDetailView,
    PositionUpdateView,
    PositionDeleteView,

    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,

    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,

    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCreateView,
)

urlpatterns = [
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/<int:pk>/edit/", PositionUpdateView.as_view(), name="position-edit"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),

    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task-types/<int:pk>/edit/", TaskTypeUpdateView.as_view(), name="task-type-edit"),
    path("task-types/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/edit/", WorkerUpdateView.as_view(), name="worker-edit"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),

    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task-edit"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
]

app_name = "todo"

templates/includes/core_js_scripts.html
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

templates/includes/footer.html
<footer style="background-color: #101213">
  <div class="container">
    <div class=" row">
      <div class="col-md-3 mb-4 ms-auto">
      </div>
      <div class="col-12">
        <div class="text-center">
          <p class="text-dark my-4 text-sm font-weight-normal">
            <p><strong>Created 2023</strong></p>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/header.html
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
<link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/favicon.png">

<link rel="stylesheet" href="{{ ROOT_DIR }}/static/css/styles.css">
<link rel="stylesheet" type="text/css"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>

<link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet"/>
<link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet"/>

<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<link id="pagestyle" href="{{ ASSETS_ROOT }}/css/material-kit.css?v=3.0.0" rel="stylesheet"/>

{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

templates/includes/navigation.html
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4 info-blur">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip"
             title="Designed and Coded by Creative Tim" data-placement="bottom">
            Home
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'todo:position-list' %}">
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom">Positions</p>
                </a>
              </li>

              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'todo:task-type-list' %}">
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom">Task types</p>
                </a>
              </li>
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'todo:worker-list' %}">
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom">Employees</p>
                </a>
              </li>
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'todo:task-list' %}">
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom">All tasks</p>
                </a>
              </li>
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'todo:task-create' %}"
                   class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">Add Task</a>
              </li>
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2"
                   href="{% url 'todo:worker-detail' pk=user.id %}">
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom">{{ user.username }}</p>
                </a>
              </li>


              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'login' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom">Logout</p>
                  </a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>