task_manager_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todo.views import index, toggle_join_task

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", index),
    path("", include("todo.urls", namespace="todo")),
    path("tasks/<int:pk>/toggle-join-task/", toggle_join_task, name="toggle-join-task")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path

from todo.views import (
    PositionListView,
    PositionDetailView,
    PositionUpdateView,
    PositionDeleteView,

    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,

    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,

    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCreateView,
)

urlpatterns = [
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/<int:pk>/edit/", PositionUpdateView.as_view(), name="position-edit"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),

    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task-types/<int:pk>/edit/", TaskTypeUpdateView.as_view(), name="task-type-edit"),
    path("task-types/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/edit/", WorkerUpdateView.as_view(), name="worker-edit"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),

    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task-edit"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
]

app_name = "todo"

todo/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        default_related_name = "task_types"

    def __str__(self) -> str:
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        default_related_name = "positions"

    def __str__(self) -> str:
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(to=Position, on_delete=models.CASCADE, null=True)

    class Meta:
        default_related_name = "workers"

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


class Task(models.Model):
    PRIORITIES = (
        ("L", "🟢"),
        ("M", "🟡"),
        ("H", "🔴"),
    )

    TASK_PROGRESS = (
        ("0", "To Do"),
        ("1", "Doing"),
        ("2", "Done")
    )

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    completing_step = models.CharField(max_length=1, choices=TASK_PROGRESS)
    priority = models.CharField(max_length=1, choices=PRIORITIES)

    task_type = models.ForeignKey(to=TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(to=Worker)

    class Meta:
        default_related_name = "tasks"

    def __str__(self) -> str:
        return self.name

todo/forms.py
from django import forms
from django.contrib.auth import get_user_model

from todo.models import Task


class TaskForm(forms.ModelForm):
    workers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Task
        fields = "__all__"


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by task name"})
    )

todo/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskSearchForm
from todo.models import Worker, Task, Position, TaskType


@login_required
def index(request):
    worker_count = Worker.objects.count()
    to_do_count = Task.objects.filter(completing_step=0).count()
    doing_count = Task.objects.filter(completing_step=1).count()
    done_count = Task.objects.filter(completing_step=2).count()

    context = {
        "worker_count": worker_count,
        "to_do_count": to_do_count,
        "doing_count": doing_count,
        "done_count": done_count,
    }
    return render(request, "todo/index.html", context=context)


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    queryset = Position.objects.prefetch_related("workers")


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("todo:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("todo:position-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    queryset = TaskType.objects.prefetch_related("tasks")
    template_name = "todo/task_type_list.html"
    context_object_name = "task_type_list"


class TaskTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = TaskType
    template_name = "todo/task_type_detail.html"
    context_object_name = "task_type_detail"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    manage = TaskType
    fields = "__all__"
    template_name = "todo/task_type_form.html"
    context_object_name = "task_type_form"
    queryset = TaskType.objects.all()
    success_url = reverse_lazy("todo:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    manage = TaskType
    template_name = "todo/task_type_confirm_delete.html"
    context_object_name = "task_type_confirm_delete"
    queryset = TaskType.objects.all()
    success_url = reverse_lazy("todo:task-type-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    queryset = Worker.objects.prefetch_related("position", "tasks")


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related("tasks")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    fields = ("first_name", "last_name", "username", "email", "position")
    success_url = reverse_lazy("todo:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("todo:worker-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = (
            Task.objects
            .select_related("task_type")
            .prefetch_related("assignees")
        )
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.prefetch_related("assignees")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


@login_required
def toggle_join_task(request, pk):
    me = get_user_model().objects.get(id=request.user.id)
    current_task = Task.objects.get(id=pk)
    if (
        me in current_task.assignees.all()
    ):
        current_task.assignees.remove(me)
    else:
        current_task.assignees.add(me)
    return redirect(request.META.get("HTTP_REFERER"))

templates/todo/index.html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">
<title>Home</title>
{% include 'includes/header.html' %}
<body class="presentation-page bg-gray-200">
<style>
    a {
        color: rgb(161, 186, 211) !important;
    }
    a:hover {
        color: red !important;
    }



  </style>
  {% include 'includes/navigation.html' %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Task Manager</h1>
            <p class="lead text-white mt-3">For devs, QA and others
                <br /> Join {{ worker_count }} developers </p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state1" countTo="{{ done_count }}">0</h1>
                  <h5 class="mt-3">Completed</h5>
                  <p class="text-sm font-weight-normal">Done tasks</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state2" countTo="{{ doing_count }}">0</h1>
                  <h5 class="mt-3">Doing</h5>
                  <p class="text-sm font-weight-normal">Processing tasks</p>
                </div>
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state3" countTo="{{ to_do_count }}">0</h1>
                  <h5 class="mt-3">To do</h5>
                  <p class="text-sm font-weight-normal">Tasks in plans</p>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </section>

  </div>
  {% include 'includes/footer.html' %}
  {% include 'includes/core_js_scripts.html' %}
</body>

</html>

templates/todo/position_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Delete position</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Delete {{ position }}
  </h3>
{% endblock %}

{% block card-content %}
      <p><strong>Are you sure?</strong></p>
      <p><strong>You'll lose all employees with this position too</strong></p>
      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn btn-outline-danger">
        <a href="{% url 'todo:position-detail' pk=position.id %}" class="btn btn-outline-success">Back</a>
      </form>
{% endblock %}

templates/todo/position_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>Position detail</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Position detail
  </h3>
{% endblock %}

{% block card-content %}




  <p><strong>Name:</strong> {{ position }}</p>
  <p><strong>Count employees with this position:</strong> {{ position.workers.count }}</p>
  <p>
    <strong>Employees:</strong>
    {% for employee in position.workers.all %}
      <a href="{% url 'todo:worker-detail' pk=employee.id %}">
        {{ employee }},
      </a>
    {% endfor %}
      <p>
      <a href="{% url 'todo:position-delete' pk=position.id%}" class="btn btn-outline-danger color text-danger">Delete</a>
      <a href="{% url 'todo:position-edit' pk=position.id%}" class="btn btn-outline-success">Edit</a>
        <a href="{% url 'todo:position-list'%}" class="btn btn-outline-success">Cancel</a>
      </p>
{% endblock %}

templates/todo/position_list.html
{% extends 'base.html' %}

{% block title %}
  <title>Position list</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Position list
  </h3>
{% endblock %}

{% block card-content %}
  <table class="table">

    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Count employees</th>
    </tr>
    </thead>

    <tbody>
    {% for position in position_list %}
      <tr onclick="window.location='{% url 'todo:position-detail' pk=position.id %}'"
          class="clickable-row">
        <td>{{ position }}</td>
        <td>{{ position.workers.count }}</td>
      </tr>
    {% endfor %}
    </tbody>

  </table>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Delete Position</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">Delete Position</h3>
{% endblock %}

{% block card-content %}
  <p><strong>Are you sure?</strong></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'todo:task-detail' pk=task.id %}" class="btn btn-outline-success">Back</a>

  </form>
{% endblock %}

templates/todo/task_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>Task detail</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Task detail
  </h3>
{% endblock %}

{% block card-content %}
  <p><strong>Aim:</strong> {{ task }} {{ task.get_priority_display }}</p>
  <p><strong>Deadline:</strong> {{ task.deadline }}</p>
  <p><strong>Task Type:</strong> {{ task.task_type }}</p>
  <p><strong>Status:</strong> {{ task.get_completing_step_display }}</p>
  <p><strong>Description:</strong> {{ task.description }}</p>
  <p><strong>Members:</strong>
    {% for member in  task.assignees.all %}
      <span>
                  <a href="{% url 'todo:worker-detail' pk=member.id %}">
                    {% if member.id == user.id %}
                      Me
                    {% else %}
                      {{ member }} ({{ member.username }})
                    {% endif %}
                  </a>,
                  </span>
    {% empty %}
      No members
    {% endfor %}
  </p>


  <p>
    {% if user in task.assignees.all %}
      {% csrf_token %}
      <a href="{% url 'toggle-join-task' pk=task.id %}"
         class="btn btn-outline-primary border-danger color text-danger">
        Leave
      </a>
    {% else %}
      <a href="{% url 'toggle-join-task' pk=task.id %}"
         class="btn btn-outline-primary border-success color text-success">
        Join
      </a>
    {% endif %}
    <a href="{% url 'todo:task-delete' pk=task.id %}"
       class="btn btn-outline-danger color text-danger">Delete</a>
    <a href="{% url 'todo:task-edit' pk=task.id %}" class="btn btn-outline-success">Edit</a>
    <a href="{% url 'todo:task-list' %}" class="btn btn-outline-success">Back</a>
  <p>
{% endblock %}

templates/todo/task_form.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ object|yesno:"Update,Add" }} Task</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">{{ object|yesno:"Update,Add" }} Task</h3>
{% endblock %}

{% block card-content %}
  <div class="card-body">
    {% load crispy_forms_filters %}
    <form action="" method="post" novalidate>
      {% csrf_token %}
      <div class="input-group input-group-static mb-4">
      </div>
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/todo/task_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}
  <title>Task list</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Task list
  </h3>
{% endblock %}

{% block card-content %}
  <div style="display: inline-block">
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="🔍" class="btn btn-outline-success color success">
  </form>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Task name</th>
      <th scope="col">Priority</th>
      <th scope="col">Deadline</th>
      <th scope="col">Task Type</th>
      <th scope="col">Step</th>
      <th scope="col">Action</th>

    </tr>
    </thead>
    <tbody>
    {% for task in task_list %}
      <tr onclick="window.location='{% url 'todo:task-detail' pk=task.id %}'" class="clickable-row">
        <td>{{ task.name }}</td>
        <td>{{ task.get_priority_display }}</td>
        <td>{{ task.deadline }}</td>
        <td>{{ task.task_type }}</td>
        <td>{{ task.get_completing_step_display }}</td>
        <td>
          {% if user not in task.assignees.all %}
            {% csrf_token %}
            <a href="{% url 'toggle-join-task' pk=task.id %}"
               class="btn btn-outline-primary border-success color text-success">
              Join
            </a>
          {% else %}
            <a href="{% url 'toggle-join-task' pk=task.id %}"
               class="btn btn-outline-primary border-danger color text-danger">
              Leave
            </a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/todo/task_type_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Delete Task type</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Delete {{ task_type_confirm_delete }}
  </h3>
{% endblock %}

{% block card-content %}
      <p><strong>Are you sure?</strong></p>
      <p><strong>You'll lose all tasks with this task type too</strong></p>
      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn btn-outline-danger">
        <a href="{% url 'todo:task-type-detail' pk=task_type_confirm_delete.id %}" class="btn btn-outline-success">Back</a>
      </form>
{% endblock %}

templates/todo/task_type_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>Task Type Detail</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Task Type Detail
  </h3>
{% endblock %}

{% block card-content %}
  <p><strong>Type:</strong> {{ task_type_detail }}</p>
  <p><strong>Count such tasks:</strong> {{ task_type_detail.tasks.count }}</p>
  <p>
    <strong>Tasks:</strong>
    {% for task in task_type_detail.tasks.all %}
      <a href="{% url 'todo:task-detail' pk=task.id %}">
        {{ task }}{{ task.get_priority_display }},
      </a>
    {% endfor %}
  </p>
  <a href="{% url 'todo:task-type-delete' pk=task_type_detail.id%}" class="btn btn-outline-danger color text-danger">Delete</a>
  <a href="{% url 'todo:task-type-edit' pk=task_type_detail.id %}" class="btn btn-outline-success">Edit</a>
    <a href="{% url 'todo:task-type-list' %}" class="btn btn-outline-success">Back</a>
{% endblock %}

templates/todo/task_type_form.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ object|yesno:"Update,Add" }} Task Type</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">{{ object|yesno:"Update,Add" }} Task Type</h3>
{% endblock %}

{% block card-content %}
  <div class="card-body">
    {% load crispy_forms_filters %}
    <form action="" method="post" novalidate>
      {% csrf_token %}
      <div class="input-group input-group-static mb-4">
      </div>
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/todo/task_type_list.html
{% extends 'base.html' %}

{% block title %}
  <title>Task list</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Task list
  </h3>
{% endblock %}

{% block card-content %}
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Task Type name</th>
      <th scope="col">Count such tasks</th>

    </tr>
    </thead>
    <tbody>
    {% for task_type in task_type_list %}
      <tr onclick="window.location='{% url 'todo:task-type-detail' pk=task_type.id %}'"
          class="clickable-row">
        <td>{{ task_type.name }}</td>
        <td>{{ task_type.tasks.count }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/todo/worker_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>Employee detail</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">
    Employee detail
  </h3>
{% endblock %}

{% block card-content %}
  <p><strong>Full Name:</strong> {{ worker.first_name }} {{ worker.last_name }}</p>
  <p><strong>Position:</strong> {{ worker.position }}</p>
  <p><strong>Email:</strong> {{ worker.email }}</p>
  <p><strong>Task Count:</strong> {{ worker.tasks.count }}</p>
  <p>
    <strong>Tasks:</strong>
    {% for task in worker.tasks.all %}
      <a href="{% url 'todo:task-detail' pk=task.id %}">
        {{ task }}{{ task.get_priority_display }},
      </a>
    {% empty %}
      No found tasks
    {% endfor %}
  </p>
  {% if user.id == worker.id %}
    <a href="{% url 'todo:worker-delete' pk=worker.id %}" class="btn btn-outline-danger color text-danger">Delete</a>
    <a href="{% url 'todo:worker-edit' pk=worker.id %}" class="btn btn-outline-success">Edit</a>
  {% endif %}
  <a href="{% url 'todo:worker-list' %}" class="btn btn-outline-success">Cancel</a>
{% endblock %}

templates/todo/worker_form.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ object|yesno:"Update,Add" }} Employee</title>
{% endblock %}

{% block card-title %}
  <h3 class="text-white text-primary mb-0">{{ object|yesno:"Update,Add" }} Employee</h3>
{% endblock %}

{% block card-content %}
  <div class="card-body">
    {% load crispy_forms_filters %}
    <form action="" method="post" novalidate>
      {% csrf_token %}
      <div class="input-group input-group-static mb-4">
      </div>
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}